### ISSUE TITLE
How to use EdgeXFoundry Security Service ?

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-compose#113]
That was my first time try to use it .I pulled this [docker-compose](https://github.com/edgexfoundry/edgex-compose/blob/master/docker-compose.yml) file the other day and started it. I met some problems. I consulted the documents, but the problems haven't been solved yet. I hope you can help me.

Problem description：
1. After i ran`docker-compose up -d`， I found that the `edgex-proxy-setup `service exited, Exit0. Is this normal ？
![exito](https://user-images.githubusercontent.com/25740210/120580929-8a39a100-c45c-11eb-9dcf-653fd979ca42.png)

2. I consult this [documents](https://docs.edgexfoundry.org/2.0/microservices/security/Ch-SecretStore/), When i run docker-compose up -d volume / config-seed 。The console print the log :ERROR: No such service: volume / config-seed。Is this document still suitable for the current version?

3. I checked the log of vault. I don't know if the initialization is normal, but I see Vault launch successfully and Vault key/value store secret successfully mounted.
![vaultlog1](https://user-images.githubusercontent.com/25740210/120583761-67f65200-c461-11eb-9a65-e9c4242294e3.png)

4. And i found some Errors . Some microservices  failed to revoke entry. The console print the log :  /xxx/ error="failed to revoke entry: resp: (*logical.Response)(nil) err: Unexpected response code: 500 (The ACL system is currently in legacy mode.)"
![vaultlog2](https://user-images.githubusercontent.com/25740210/120583889-9b38e100-c461-11eb-8752-23eb9429911e.png)

Am I setting something wrong? What should I do？

5. When I access Consul or Vault and need tocken to log in, how can I get the tocken ？
![consul](https://user-images.githubusercontent.com/25740210/120584428-8c9ef980-c462-11eb-86e5-b5a97db8630c.png)
![vault](https://user-images.githubusercontent.com/25740210/120584432-90328080-c462-11eb-84a5-f7e9b08ebbdd.png)

I'd appreciate it if you could give me some help. Thanks!

**Comment by bnevis-i** [comment]
1. Yes, `edgex-proxy-setup` is a one-shot service that does its job and then exits (with hopefully 0 exit code)
2. Yes. `edgex-volume` and `config-seed` are both gone.  Doc updates are needed.
3. This step is working correctly.
4. I think we should look at this one but it won't impair your functionality
5. We stash away a Consul management token in secure mode.  We're planning to add a utility function somewhere to get at it a little easier.  In the meantime, see below:

```console
# docker run --rm -ti -v edgex_consul-acl-token:/acl alpine:latest cat /acl/bootstrap_token.json
```

**Comment by jim-wang-intel** [comment]
> 1. Yes, `edgex-proxy-setup` is a one-shot service that does its job and then exits (with hopefully 0 exit code)
> 2. Yes. `edgex-volume` and `config-seed` are both gone.  Doc updates are needed.
> 3. This step is working correctly.
> 4. I think we should look at this one but it won't impair your functionality
> 5. We stash away a Consul management token in secure mode.  We're planning to add a utility function somewhere to get at it a little easier.  In the meantime, see below:
> 
> ```
> # docker run --rm -ti -v edgex_consul-acl-token:/acl alpine:latest cat /acl/bootstrap_token.json
> ```

To add the comments **on the step** 5 above, you can do `make get-consul-acl-token` under the compose-builder folder. See the documentation in this section:   https://github.com/edgexfoundry/edgex-compose/blob/master/compose-builder/README.md#get-consul-acl-token

**Comment by FengZeHe** [comment]
> 1. 是的，`edgex-proxy-setup`是一种一次性服务，可以完成其工作然后退出（希望退出代码为 0）
> 2. 是的。`edgex-volume`并且`config-seed`都不见了。需要更新文档。
> 3. 这一步工作正常。
> 4. 我认为我们应该看看这个，但它不会损害您的功能
> 5. 我们在安全模式下隐藏了 Consul 管理令牌。我们计划在某处添加一个实用程序函数以使其更容易一些。在此期间，请参阅以下内容：
> 
> ```
> # docker run --rm -ti -v edgex_consul-acl-token:/acl alpine:latest cat /acl/bootstrap_token.json
> ```


Thank you so much ! I'll have a try.
