### ISSUE TITLE
get-api-gateway-token.sh has bug in unique ID generation

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-compose#114]
`get-api-gateway-token.sh`

The code is currently generating a unique JWT ID with the literal string "uuidgen" instead of a unique string output by the `uuidgen` command.

This

```sh
ID="uuidgen"

docker run --rm -it -e KONGURL_SERVER=kong -e "ID=${ID}" -e "JWT_FILE=${JWT_FILE}" --network edgex_edgex-network --entrypoint "" -v ${GW_KEY_DIR}:/keys -v ${JWT_VOLUME}:${JWT_VOLUME} \
       ${CORE_EDGEX_REPOSITORY}/security-proxy-setup${ARCH}:${CORE_EDGEX_VERSION}${DEV} \
        /bin/sh -c 'JWT=`cat ${JWT_FILE}`; /edgex/secrets-config proxy adduser --token-type jwt --id ${ID} --algorithm ES256  --public_key /keys/gateway.pub \
              --user gateway --group gateway --jwt ${JWT} > /dev/null'

docker run --rm -it -e KONGURL_SERVER=kong -e "ID=${ID}" --network edgex_edgex-network --entrypoint "" -v ${GW_KEY_DIR}:/keys \
       ${CORE_EDGEX_REPOSITORY}/security-proxy-setup${ARCH}:${CORE_EDGEX_VERSION}${DEV} \
       /bin/sh -c '/edgex/secrets-config proxy jwt --algorithm ES256 --id ${ID} --private_key /keys/gateway.key'
```

should be

```sh
ID=`uuidgen`

(unchanged)
```

**Comment by jim-wang-intel** [comment]
@bnevis-i  so I am not sure that ID should be generated from the host system and then pass into the docker container.
The current way is that it generates the UUID inside the docker container on the fly so that it reduces the chance of ID collision from the host system if that were the case.

**Comment by jim-wang-intel** [comment]
ok @bnevis-i  showed me the running it with echo ${ID} inside the docker container and it does show the literal string `uuidgen` 
So confirm that it is a bug. Thanks Bryon!
