### ISSUE TITLE
SMA cannot execute docker command on CentOS

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#124]
Got an error `exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied` when retrieving service metrics and execting operation by system-agent. Please reference [edgexfoundry/edgex-taf issue #463](https://github.com/edgexfoundry/edgex-taf/issues/463).

This issue only happened in `CentOS` environment, not ubuntu. I got a similar error last year on Jenkins x86_64 environment and fixed it by adding `--security-opt label:disable` in docker command. I tried to add `"label:disable"` under system/security_opt and ran it on `Jenkins sandbox`, the error got to fix.

Could we add the parameter under system service or any solution for the issue?

Reference [Linux Foundation Ticket IT-19912](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-19912) if you have permission to open it.

**Comment by cloudxxx8** [comment]
This might also happen on other OS, but it works fine on Ubuntu.

**Comment by lenny-intel** [comment]
@bnevis-i , are you ok with this?

**Comment by bnevis-i** [comment]
Going to regress this on CentOS.  Which version does this occur on?

**Comment by lenny-intel** [comment]
From the  linked LF ticket it looks like centos7 and above? Not sure which version the TAF tests are currently running on.

**Comment by bnevis-i** [comment]
Additional information:

- Docker SElinux supports needs to be explicitly enabled. <https://www.arhea.net/posts/2020-04-28-selinux-for-containers.html>  It is not enabled out-of-the-box when installing Docker on an SE-linux enabled CentOS.

- Once enabled there is a label conflict between the container and the socket. <https://bugzilla.redhat.com/show_bug.cgi?id=1557893>
