### ISSUE TITLE
Got error "failed to get Configuration Provider (consul) access token" when using taf-perf compose file to restart service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#127]
Reproduce steps:
1. Download the [taf/docker-compose-taf-perf.yml](https://github.com/edgexfoundry/edgex-compose/blob/425a1f9a53395aa5d0ba8ac0a73229c065629488/taf/docker-compose-taf-perf.yml).
2. Execute command `docker-compose -f docker-compose-taf-perf.yml up -d`
3. Execute command `docker-compose -f docker-compose-taf-perf.yml restart`

Error:

Services that need to register to consul startup failed with error `failed to get Configuration Provider (consul) access token: HTTP response with status code 400, message: failed to generate Consul token using [core-data]: {\"errors\":[\"Unexpected response code: 500 (The ACL system is currently in legacy mode.)\"]}\n`

**Comment by cherrycl** [comment]
Tried to run the same steps on [docker-compose.yaml](https://github.com/edgexfoundry/edgex-compose/blob/master/docker-compose.yml) file. This issue happened sometimes.

**Comment by lenny-intel** [comment]
@cherrycl , if you do 
`docker-compose -f docker-compose-taf-perf.yml down`
`docker-compose -f docker-compose-taf-perf.yml up -d`
instead of 
`docker-compose -f docker-compose-taf-perf.yml restart`
does it work better?

We know there are issues with restarting services that we plan on addressing in `jarkarta`

**Comment by lenny-intel** [comment]
The problem is we can't control the order of the restarts when using `restart` , so some services get restarted before or as secret store setup is revoking and regenerating tokens. If a service picks up on the old taken it will get this error since secret store setup has revoked it before it uses it. @bnevis-i , @jim-wang-intel , do you agree with this assessment?

For now you will need to use the work around of `down` then `up`

**Comment by jim-wang-intel** [comment]
> The problem is we can't control the order of the restarts when using `restart` , so some services get restarted before or as secret store setup is revoking and regenerating tokens. If a service picks up on the old taken it will get this error since secret store setup has revoked it before it uses it. @bnevis-i , @jim-wang-intel , do you agree with this assessment?
> 
> For now you will need to use the work around of `down` then `up`

yea, I agree with you, @lenny-intel  on your assessment.  The docker-compose restart may not serve the best purpose for `security-bootstrapper` as it may not be the first one to restart now (in which the order is critical if it really gets restarted)...

**Comment by bnevis-i** [comment]
> The problem is we can't control the order of the restarts when using `restart` , so some services get restarted before or as secret store setup is revoking and regenerating tokens. If a service picks up on the old taken it will get this error since secret store setup has revoked it before it uses it. @bnevis-i , @jim-wang-intel , do you agree with this assessment?
> 
> For now you will need to use the work around of `down` then `up`

Agree.  Security-bootstrapper won't help here as it will probably notice all the services are up and sail right through.

**Comment by cherrycl** [comment]
> @cherrycl , if you do
> `docker-compose -f docker-compose-taf-perf.yml down`
> `docker-compose -f docker-compose-taf-perf.yml up -d`
> instead of
> `docker-compose -f docker-compose-taf-perf.yml restart`
> does it work better?
> 
> We know there are issues with restarting services that we plan on addressing in `jarkarta`

@bnevis-i Yes. Use stop/down then start/up instead of restart. It works well.

**Comment by lenny-intel** [comment]
@cherrycl , great! Can we close this issue then?

**Comment by cherrycl** [comment]
@lenny-intel Sure and thank you.
