### ISSUE TITLE
No device-virtual credential found when deploy edgex by TAF related compose files

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#132]
**Reproduce Steps:**
Deploy edgex with security enabled using compose files under taf folder.

**Actual Result:**
device-virtual down and found the error in the logs.
**Found error **level=ERROR ts=2021-06-18T03:18:20.741293829Z app=device-virtual source=messaging.go:48 msg="Unable to get Secret Data for secure message bus: Error found on handling secrets from underlying data-store: Received a '404' response from the secret store"****

**Comment by cloudxxx8** [comment]
The redis credential should be added to
https://github.com/edgexfoundry/edgex-compose/blob/feab786bd1218bc0ece9c65253132a633a06397c/compose-builder/Makefile#L304
https://github.com/edgexfoundry/edgex-compose/blob/feab786bd1218bc0ece9c65253132a633a06397c/compose-builder/Makefile#L355
