### ISSUE TITLE
[Makefile] Clean deletes non-EdgeX volumes

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/edgex-compose#156]
`make clean` performs a `docker volume prune -f` without regard for where those volumes came from. It should be scoped to remove just EdgeX related volumes, otherwise it has the potential to be very destructive, especially without a warning and confirmation.

https://github.com/edgexfoundry/edgex-compose/blob/e6214824317653e6520091d4b39a0c4f586b5260/Makefile#L59-L62

**Comment by lenny-intel** [comment]
This removes only unused containers, volumes and networks, if the containers, volumes and networks are in use it will not remove them.

Also, this is meant for developers not production use.

**Comment by lenny-intel** [comment]
Looks like we can accomplish all of this with the `-v` option `docker-compose down` :-)
