### ISSUE TITLE
how to upload device profile with REST API

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/edgex-compose#162]
hi ,I looked it up [here](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0#/), and i'm going to upload a device profile. 
![image](https://user-images.githubusercontent.com/25740210/127625217-fa869313-0367-4f0a-a896-6bf405a00385.png)
![image](https://user-images.githubusercontent.com/25740210/127625572-4cc79aab-0308-4e8d-9f4f-900e56a0d230.png)
And this is the device profile.
![image](https://user-images.githubusercontent.com/25740210/127625881-59e0d961-177c-41bf-b062-c706119d90a0.png)

Why does it return " missing yaml file" ?

**Comment by cloudxxx8** [comment]
the key is `file`, not `deviceprofile`
we will update the API document to make it clear
![image](https://user-images.githubusercontent.com/11695863/127627775-4ef17bdc-cdac-43dc-ae78-73cbc305c16c.png)

**Comment by FengZeHe** [comment]
> the key is `file`, not `deviceprofile`
> we will update the API document to make it clear
> ![image](https://user-images.githubusercontent.com/11695863/127627775-4ef17bdc-cdac-43dc-ae78-73cbc305c16c.png)

Thanks for your reply. Now I have uploaded it successfully.
