### ISSUE TITLE
Content inconsistent from the compose-builder folder make build result

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-compose#180]
After running `make build` from the compose-builder folder, the generated content is inconsistent with the current docker-compose files.  In this case, people need to manually modify the files if they want to open PRs.
I create a draft PR to show the differences from my environment:  https://github.com/edgexfoundry/edgex-compose/pull/179/files

This issue might be caused by the different version of docker-compose
I am using 
$ docker-compose -v
docker-compose version 1.27.4, build 40524192

$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by lenny-intel** [comment]
@cloudxxx8 Yes, this is a know issue with the latest docker-compose. I have mentioned previously that we must use docker-compose 1.27.2 which generates the depends-on sections correctly. Based on my research they don't plan to fix this issue.

**Comment by cloudxxx8** [comment]
@lenny-intel should we update the compose-builder in Readme to indicate the recommended docker-compose version?

**Comment by lenny-intel** [comment]
> @lenny-intel should we update the compose-builder in Readme to indicate the recommended docker-compose version?

@cloudxxx8 , Agreeded.

**Comment by lenny-intel** [comment]
@cloudxxx8 , README has been updated. Can we now close this issue and the related PR?

**Comment by cloudxxx8** [comment]
Sure, thanks
