### ISSUE TITLE
Consul not persisting data between down and up in non-secure mode

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-compose#186]
The command needs to be set to `command: "agent -ui -bootstrap -server -client 0.0.0.0"` in the compose file since the default in the image is using `-dev` which doesn't persist the data.

In secure mode the entry-point script is doing the `"agent -ui -bootstrap -server -client 0.0.0.0"`

**Comment by lenny-intel** [comment]
@JamesKButcher, @jpwhitemn , we need to discuss this in next Core WG for regarding patching Ireland. 
It is just a change in the compose files, but we have no strategy for versioning of the compose files for patches.

**Comment by cloudxxx8** [comment]
I thought using a GitHub tag in edgex-compose could resolve this issue.  We have already had 2.0.0 tag, and we should tag the current ireland branch to 2.0.1, and tag 2.0.2 after adding this new fix.
