### ISSUE TITLE
docker-compose without security needs to add EDGEX_SECURITY_SECRET_STORE to edgex-ui-go

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-compose#199]
The no-security docker-compose files for Jakarata need to add the EDGEX_SECURITY_SECRET_STORE=false to the ui container as it now will require the token to get access with security on.

**Comment by lenny-intel** [comment]
@jpwhitemn,  Now that the UI works with both secure and non-secure, do we want to add it to the base set of services so that it now always available in all our reference compose files?

Doing this makes the fix for this simpler. :-)

**Comment by jpwhitemn** [comment]
Given GUI is still considered dev/demo only, I think this is premature.  Having said that, if the TSC is ok with it, I am ok with it as I don't think it's too hard to just comment it out if you don't need it.
