### ISSUE TITLE
Provide a TUI for custom generation of docker-compose files

### ISSUE THREAD

**Issue by shantanoo-desai** [edgexfoundry/edgex-compose#225]
## Idea
Since there are a lot of components that are part of EdgeX Foundry, providing a TUI (Terminal User Interface) using `whiptail` may help define Developer as well as Usage Workflow for the `compose-builder` component of the repository.

By using a TUI, the user may be free to choose any of the following for their custom stack:

1. which Device Services they wish to incorporate
2. which App Services they wish to incorporate
3. Whether they wish to change the underlying data-bus
4. If they wish to introduce General / Specific Service e.g. `mqtt-broker`

### Implementation
Potential introduction of `tui-generator.sh` bash script which maps the services and components listed in the `compose-builder` folder and leverages the `make gen <component>` command to generate the dedicated `docker-compose.yml` file

### Initial Experiments
The following GIF describes a potential UI using `whiptail`. The component options are mapped according to descriptions in the `compose-builder`'s `README.md` file.

![EdgexFoundry-ComposeBuilder-TUI](https://user-images.githubusercontent.com/12070966/159784671-129c00e1-18d8-4627-b144-bbc5c3680851.gif)

## Future Actions
If approved, a PR with the `tui-generator.sh` file with some implementation will be created, and the potential UI changes and flows will be incorporated based on feedback on this Issue.

**Comment by lenny-intel** [comment]
@shantanoo-desai , please submit the PR so we can see this in action and play with it. Thanks!

**Comment by shantanoo-desai** [comment]
## Usage Flow for TUI
One of the reason, the following Usage Flow is chosen is to avoid overriding services that may cause errors when bringing the stack up.

### Description
1. Start with determining which architecture the images should be built for (`arm64`)
2. Ask whether user wishes to use the no-secure-configuration (`no-secty`)
3. Ask whether to add Device Services
4. Ask whether to add App Services
5. Ask whether to update the Message Bus (`mqtt-bus`, `zmq-bus`). Since it can be either one, radio list is used.
6. Ask whether the user wishes to add some additonal services (`mqtt-broker`, `modbus-sim`)

![EdgeXFoundryTUIUsageFlow](https://user-images.githubusercontent.com/12070966/160210491-225b6564-d9ea-4f3b-aef9-0611c7d53662.png)

**Comment by shantanoo-desai** [comment]
# Result
Initial result of `./tui-generator.sh` based on the Usage Flow
![TUIGeneratorEdgeXFoundry_v1_result](https://user-images.githubusercontent.com/12070966/160211678-ed9c075b-6f63-48ae-baa5-956a9b303542.gif)

**Comment by shantanoo-desai** [comment]
# Result
Initial result of `./tui-generator.sh` based on the Usage Flow
![TUIGeneratorEdgeXFoundry_v1_result](https://user-images.githubusercontent.com/12070966/160211678-ed9c075b-6f63-48ae-baa5-956a9b303542.gif)
