### ISSUE TITLE
level=ERROR ts=2022-06-20T14:48:47.4290073Z app=secrets-config source=bootstraphandler.go:76 msg="Create consumer request failed with code: 503"

### ISSUE THREAD

**Issue by prateekgml** [edgexfoundry/edgex-compose#253]
Hi,

I am trying to generate JWT token by following below document:
[https://docs.edgexfoundry.org/2.1/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication](url)

And on the step 'Register a user for that key' after running the command `docker-compose -p edgex -f docker-compose.yml run --rm -v `pwd`:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy adduser --token-type jwt --id "$ID" --algorithm ES256 --public_key /host/ec256.pub --user _SOME_USERNAME_ --jwt "$KONGJWT"` I am getting below error-

![image](https://user-images.githubusercontent.com/97145738/174635066-d96c3044-0c51-4576-991d-a2ec24d0eb2b.png)

After this I ran the next step command `docker-compose -p edgex -f docker-compose.yml run --rm -v `pwd`:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy jwt --id "$ID" --algorithm ES256 --private_key /host/ec256.key` and it is generating the token but with some warn/error-

![image](https://user-images.githubusercontent.com/97145738/174635319-62e283c0-3c93-4c9f-b6d5-5ba65f6505ad.png)

But when I used that generated token as below, it is saying no credentials found for this iss-

![image](https://user-images.githubusercontent.com/97145738/174635775-cbecee55-0675-41ba-92b5-11e5d6e8c765.png)

Please help if I am doing anything wrong here.

**Comment by lenny-intel** [comment]
@prateekgml , what version of `docker-compose` are you using?
The output looks like you have `docker-compose` aliased to the new V2 `compose` command in docker CLI. Is this correct?
If so, we don't yet support V2 as no one has tested the commands given in the referenced documentation with V2 docker compose..

**Comment by bnevis-i** [comment]
Instead of running ** --entrypoint "/edgex/secrets-config" **.   Try running sh and see if it can resolve Edgex-vault.    I think it is having a name resolution issue that is blocking registering the key.   It can always generate the jet because you have the private key locally.

**Comment by lenny-intel** [comment]
@prateekgml , also what environment are you running in? 
I have been seeing this same issue when running in WSL (rather than a real Linux system) since we added `KONG_DNS_VALID_TTL: '1'` to Kong in the compose file. If I comment that line out it works fine in WSL for me.

**Comment by prateekgml** [comment]
> @prateekgml , what version of `docker-compose` are you using? The output looks like you have `docker-compose` aliased to the new V2 `compose` command in docker CLI. Is this correct? If so, we don't yet support V2 as no one has tested the commands given in the referenced documentation with V2 docker compose..

My docker-compose version is: 2.6.0 and I have installed Docker Desktop for Windows using [https://docs.docker.com/desktop/windows/install/](url)

![image](https://user-images.githubusercontent.com/97145738/174938163-db4d9b76-2a9b-49bb-ba2f-fbdee88ef527.png)

Please share the whole command to run.

**Comment by prateekgml** [comment]
> @prateekgml , also what environment are you running in? I have been seeing this same issue when running in WSL (rather than a real Linux system) since we added `KONG_DNS_VALID_TTL: '1'` to Kong in the compose file. If I comment that line out it works fine in WSL for me.

My environment is as below:

Docker Compose version: 2.6.0
OS: Windows 10 64 bit
WSL version: 2

![image](https://user-images.githubusercontent.com/97145738/174938868-c6bf97cd-1c42-4ec3-b13d-54527713f9a9.png)

Please confirm in which file I need to comment this: `KONG_DNS_VALID_TTL:1`

**Comment by prateekgml** [comment]
> `docker-compose -p edgex -f docker-compose.yml run --rm -v `pwd`:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy adduser --token-type jwt --id "$ID" --algorithm ES256 --public_key /host/ec256.pub --user _SOME_USERNAME_ --jwt "$KONGJWT"`

After commenting this line, I ran the following command:
`docker-compose -p edgex -f docker-compose.yml run --rm -v pwd:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy adduser --token-type jwt --id "$ID" --algorithm ES256 --public_key D:/edgex_poc/edgexfoundry/edgex-compose/ec256.pub --user _SOME_USERNAME_ --jwt "$KONGJWT"`

In the last line of the output, it says: `level=ERROR ts=2022-06-23T04:02:32.7530681Z app=secrets-config source=bootstraphandler.go:76 msg="failed to read public key from file`

![image](https://user-images.githubusercontent.com/97145738/175206682-1f859448-f56e-42f1-9273-2de31c5f49a0.png)

Is there any specific path to put my public key? please suggest.

**Comment by lenny-intel** [comment]
Why did you can it to `--public_key D:/edgex_poc/edgexfoundry/edgex-compose/ec256.pub `? 
Containers can not directly access your D: drive.

**Comment by prateekgml** [comment]
> Why did you can it to `--public_key D:/edgex_poc/edgexfoundry/edgex-compose/ec256.pub `? Containers can not directly access your D: drive.

Actually I tried in both ways with relative and with absolute path but error is the same.
`docker-compose -p edgex -f docker-compose.yml run --rm -v pwd:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy adduser --token-type jwt --id "$ID" --algorithm ES256 --public_key /host/ec256.pub --user _SOME_USERNAME_ --jwt "$KONGJWT"`

![image](https://user-images.githubusercontent.com/97145738/175462284-2f1cd90e-f207-4f65-b900-e3f80d4a4928.png)

**Comment by lenny-intel** [comment]
From the documentation: 
```
docker-compose -p edgex -f docker-compose.yml run --rm -v `pwd`:/host:ro -u "$UID" --entrypoint "/edgex/secrets-config" proxy-setup -- proxy adduser --token-type jwt --id "$ID" --algorithm ES256 --public_key /host/ec256.pub --user _SOME_USERNAME_ --jwt "$KONGJWT"
```

You need to have "\`pwd\`" looks like you only have "pwd". 
The "pwd" command returns to full path to the current working directory which is volume mounted to `/host` in the container. Your public key must be in the the current directory that "pwd" refers to so that it will be in the container at: /host/ec256.pub

**Comment by bnevis-i** [comment]
@prateekgml

I am going to close this as it looks like it is just a simple cut/paste mistake exacerbated by markdown formatting.  I think Lenny identified the issue that you are having.

Also make sure you check out all the code with Unix EOL characters to avoid unexplained failures in other parts of edgex.

Reopen if you still have issues.
