### ISSUE TITLE
computer vision model based use case?

### ISSUE THREAD

**Issue by prateekgml** [edgexfoundry/edgex-compose#256]
Hi,

I am new to EdgeX and my query is: 
Can we deploy any computer vision model ( for example Tensorflow model) on Edgex?
If yes, please share any supportive guide to achieve this.

If not, so suppose I deployed my computer vision model as Rest API. In this case, should I need to register my Rest API as a device in Edgex? Please share any supportive documents for this use case as well.

Besides if you have any other document or guide or suggestion based on the computer vision model use case , please also share with that.

**Comment by lenny-intel** [comment]
@prateekgml , this is not the appropriate repo for this question and I though I saw the same question post in Slack or other repo so closing it here.
