### ISSUE TITLE
init.lua:310: execute(): DNS resolution failed: dns server error: 3 name error.

### ISSUE THREAD

**Issue by tntthanh** [edgexfoundry/edgex-compose#257]
Hi everyone, I had run EdgeX docker-compose-arm64.yml on Raspberry Pi 4 and got the following error just after all docker services had started, that I can not use JSON web token generated to curl EdgeX APIs:

2022/07/12 03:38:20 [error] 6651#0: *43 [lua] init.lua:310: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)localhost:(na) - cache-hit/stale","localhost:1 - cache-hit/dns server error: 3 name error","localhost:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.20.0.9, server: kong, request: "POST /admin/services HTTP/1.1", host: "edgex-kong:8000"

Thank you very much!

**Comment by cloudxxx8** [comment]
@hahattan are you able to see what is wrong here?

**Comment by cloudxxx8** [comment]
@tntthanh could you please state which release you are using?

**Comment by tntthanh** [comment]
> @tntthanh could you please state which release you are using?

@cloudxxx8 I clone from main branch, which I see to be the latest release. 

I implement the source by following steps:
1. execute "make run arm64" (without modify docker-compose-arm64.yml file),
2. then execute "ARCH=-arm64 make get-token" to get <JWT>, 
3. and finally, I curl to core-data API with the <JWT> generated by execute:
"curl -k https://localhost:8443/core-data/api/v2/ping -H "Authorization: Bearer <JWT>" 
but receive this response **{“message”:“No credentials found for given ‘iss’”}** that meanwhile, I observe loggings of EdgeX docker's containers from command window, I see it appear the error that I raise in the issue:
**edgex-kong | 2022/07/13 02:18:12 [error] 6685#0: *134 [lua] init.lua:310: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)localhost:(na) - cache-miss","localhost:1 - cache-hit/dns server error: 3 name error","localhost:5 - cache-hit/dns server error: 3 name error"], client: 172.18.0.9, server: kong, request: "POST /admin/consumers HTTP/1.1", host: "edgex-kong:8443"**

In addition, sometime it also log this following error just on start-up when I just launch the docker-compose file too:
**edgex-security-proxy-setup | level=ERROR ts=2022-07-13T02:06:47.04580884Z app=security-proxy-setup source=init.go:53 msg="failed to set up route authentication for sys-mgmt-agent with error 503 Service Temporarily Unavailable, {\"message\":\"name resolution failed\"}"**

My Raspberry Pi 4 is ran on Raspbian 10 (Buster) OS

**Comment by cloudxxx8** [comment]
do you see sys-mgmt-agent in your docker-compose-arm64.yml?
it should be under the system entry like this:
https://github.com/edgexfoundry/edgex-compose/blob/ff85f6bff0a3f83f98ac9210ea03f3e4c814f05c/docker-compose-arm64.yml#L929

If not, could you please copy this section and try again?

**Comment by tntthanh** [comment]
@cloudxxx8 It is still not working, and I get the same error...

**Comment by cloudxxx8** [comment]
could you please provide the detailed steps about generating the token?
Is it the same as this instruction?
https://docs.edgexfoundry.org/2.2/security/Ch-APIGateway/#creating-access-token-for-api-gateway-authentication

**Comment by cloudxxx8** [comment]
also, please help confirm the error log timestamp
did it happen when you generate the token or send the ping request?

**Comment by tntthanh** [comment]
@cloudxxx8 
The error log timestamp:
edgex-kong               | 2022/07/18 01:56:10 [error] 6649#0: *35 [lua] init.lua:310: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)localhost:(na) - cache-hit/stale","localhost:1 - cache-hit/dns server error: 3 name error","localhost:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.20.0.10, server: kong, request: "POST /admin/routes/core-metadata/plugins HTTP/1.1", host: "edgex-kong:8000"
edgex-security-proxy-setup | level=ERROR ts=2022-07-18T01:56:10.245780603Z app=security-proxy-setup source=service.go:507 msg="failed to set up route authentication for core-metadata with error 503 Service Temporarily Unavailable, {\"message\":\"name resolution failed\"}"
edgex-security-proxy-setup | level=ERROR ts=2022-07-18T01:56:10.24591742Z app=security-proxy-setup source=init.go:53 msg="failed to set up route authentication for core-metadata with error 503 Service Temporarily Unavailable, {\"message\":\"name resolution failed\"}"

Generating the token is normal, I receive the key and ping to core-data, but receive response **{“message”:“No credentials found for given ‘iss’”}**, watch on the log window I see the above error log

**Comment by tntthanh** [comment]
@cloudxxx8 
The error log timestamp:
edgex-kong | 2022/07/18 01:56:10 [error] 6649#0: *35 [lua] init.lua:310: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)localhost:(na) - cache-hit/stale","localhost:1 - cache-hit/dns server error: 3 name error","localhost:5 - cache-miss/scheduled/querying/dns server error: 3 name error"], client: 172.20.0.10, server: kong, request: "POST /admin/routes/core-metadata/plugins HTTP/1.1", host: "edgex-kong:8000"
edgex-security-proxy-setup | level=ERROR ts=2022-07-18T01:56:10.245780603Z app=security-proxy-setup source=service.go:507 msg="failed to set up route authentication for core-metadata with error 503 Service Temporarily Unavailable, {"message":"name resolution failed"}"
edgex-security-proxy-setup | level=ERROR ts=2022-07-18T01:56:10.24591742Z app=security-proxy-setup source=init.go:53 msg="failed to set up route authentication for core-metadata with error 503 Service Temporarily Unavailable, {"message":"name resolution failed"}"

Generating the token is normal, I receive the key and ping to core-data, but receive response {“message”:“No credentials found for given ‘iss’”}, watch on the log window I see the above error log

**Comment by cloudxxx8** [comment]
are you able to reproduce the same issue in the Jakarta release (using jakatar branch)?

**Comment by cloudxxx8** [comment]
the issue should happen during the toke creation, because the error message means the token doesn't exist.
that's why I asked you to confirm the kong error message timing is the time you created the token or no.

**Comment by cloudxxx8** [comment]
you can try to remove this environment setting in the docker-compose file
`KONG_DNS_VALID_TTL: '1'`

we can't reproduce your issue in our arm64 environment anyway

**Comment by tntthanh** [comment]
@cloudxxx8 Removing KONG_DNS_VALID_TTL: '1' had solved my problem. Thank you very much!

**Comment by cloudxxx8** [comment]
great!
