### ISSUE TITLE
eKuiper 1.6.0 is not backward compatible

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry/edgex-compose#267]
eKuiper 1.6.0 (added in #266) is not backward compatible with respect to configuration files. See https://github.com/lf-edge/ekuiper/issues/1361

IMO, EdgeX 2.3 should not be release with this, unless it is fixed to become backward compatible.

# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: eKuiper (rules-engine)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: EdgeX 2.2.0 / eKuiper 1.5.1

### Description and Minimal Reproduction [**REQUIRED**]
Refer to https://github.com/lf-edge/ekuiper/issues/1361

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
IMO, we should wait and see if eKuiper addresses https://github.com/lf-edge/ekuiper/issues/1361
We'll discuss this with them in the next App Service working group

**Comment by farshidtz** [comment]
> IMO, we should wait and see if eKuiper addresses [lf-edge/ekuiper#1361](https://github.com/lf-edge/ekuiper/issues/1361) We'll discuss this with them in the next App Service working group

They have added it to [milestone 1.6.1](https://github.com/lf-edge/ekuiper/milestone/11?closed=1) with a [fix](https://github.com/lf-edge/ekuiper/pull/1366).

**Comment by lenny-intel** [comment]
https://github.com/lf-edge/ekuiper/pull/1366 fixes issue. Docker compose currently not pinned to patch version so doesn't change. Snaps will need to be update to patched version.
