### ISSUE TITLE
[3.0] Upgrade to Kong 3.x and Postgres 14.x

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-compose#294]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Kong and Postgres

### Description [**REQUIRED**]
 Kong 3.x and Postgres 14.x cause backwards breaking changes in EdgeX 2.x

### Describe the solution you'd like
 Upgrade to Kong 3.x and Postgres 14.x in EdgeX 3.0 when we can have the backwards breaking changes. The 3.0 Migration guide will need instructions on how to migrate Postgress DB 13.x => 14.x and possibly Kong.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
@lenny-intel @bnevis-i 
since Kong will be replaced with Nginx, may we close this issue?

**Comment by bnevis-i** [comment]
With the approval of the microservice token-based authentication ADR, this ticket is now closed!
