### ISSUE TITLE
device-camera is deprecated, use device-onvif-camera for TAF test instead

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#302]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-camera

### Description [**REQUIRED**]
 
device-camera is deprecated, use device-onvif-camera for TAF test instead

**Comment by lenny-intel** [comment]
@cherrycl , I assume the TAF scripts need to change if we does this swap, correct. 
Do you agree this should wait unit post Levski release?

**Comment by cloudxxx8** [comment]
@lenny-intel there is a test case to verify the command service should not crash if the device is unreachable.  it's easy to test with an ip based camera device service.  if onvif-camera device service need a little more time, we can wait until post Levski
https://github.com/edgexfoundry/edgex-go/issues/3716
