### ISSUE TITLE
Docker gen tool for mqtt-bus still has references to edgex-redis message queue

### ISSUE THREAD

**Issue by edge-plus** [edgexfoundry/edgex-compose#312]
# Tech Debt

### Affected Services [**REQUIRED**]

 The issue is located in: 
app-service-mqtt-export
app-service-rules
command
database
system

### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
I just tried generating a docker compose file using the following command for the levski branch

make gen no-secty ds-mqtt ds-rest asc-mqtt mqtt-bus

The generated docker-compose file has entries in the environment section of the above mentioned services to:
MESSAGEQUEUE_HOST: edgex-redis

The remaining services have correct references to:
MESSAGEQUEUE_HOST: edgex-mqtt-broker

Is this the expected behavior?  I was under the impression that there should be only one message bus.

Please clarify.

Thanks,
Marcelo Gallardo

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
Levski

**Anything else relevant?**

**Comment by lenny-intel** [comment]
Actually Core Command uses `MESSAGEQUEUE_INTERNAL_HOST: edgex-mqtt-broker` so this is not an issue, just some extra unused environment variables.

**Comment by lenny-intel** [comment]
Leaving this issue as Tech Debt to see if we can clean these up to avoid confusion.
