### ISSUE TITLE
Remove bind options from docker volume mounts

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-compose#329]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
edgex-compose

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
Get rid of these warnings:

```
docker compose  -p edgex up -d 
WARN[0000] mount of type `volume` should not define `bind` option 
```

**Comment by lenny-intel** [comment]
This is being added by `docker compose` when the files are generated.

**Comment by bnevis-i** [comment]
I was thinking it was the `:z` sharing options that we implemented for CentOS.  Probably not required for named docker volumes.

**Comment by lenny-intel** [comment]
Yep, you nailed it. If we remove all the `:z` and `,z` the volumes are generated correctly.

**Comment by bnevis-i** [comment]
Update: I need manually validate this to see if we've gone enough but not too far.
