### ISSUE TITLE
Fail to Deploy device-virtual with mqtt-bus and got error "Failed to subscribe Metadata system event"

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#331]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-service

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with attached compose file

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2023-01-30T10:00:50.167998044Z app=device-virtual source=main.go:126 msg="Failed to subscribe Metadata system event: An error occured while performing a 'Subscribe' operation: invalid Topic; multi-level wildcard must be last level"

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** x86/ubuntu

**EdgeX Version [**REQUIRED**]:** main

**Anything else relevant?**

[docker-compose-mqtt-bus.yml.zip](https://github.com/edgexfoundry/device-sdk-go/files/10534601/docker-compose-mqtt-bus.yml.zip)

**Comment by lenny-intel** [comment]
@cloudxxx8 , https://github.com/edgexfoundry/edgex-compose/pull/330
