### ISSUE TITLE
Support with docker-compose use JWT [UI:localhost:4000]

### ISSUE THREAD

**Issue by MILANOFCOFEE** [edgexfoundry/edgex-compose#362]
Hello everybody! I run docker-compose.yml with security, branch Jakarta. After I ran docker, I tried to this page: localhost:4000 and then used the command to get kong-admin 
> sudo cat /tmp/edgex/secrets/security-proxy-setup/kong-admin-jwt
<img width="479" alt="image" src="https://user-images.githubusercontent.com/128799769/230703700-0279228c-8e33-4374-9af2-fecef1b9b205.png">

But I got a problem
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/128799769/230703794-ee2a1771-9fa0-4fdc-b272-506db265db19.png">
Thank you!

**Comment by lenny-intel** [comment]
That is the wrong token. Please see the documentation here: https://docs.edgexfoundry.org/2.1/security/Ch-Secure-Consul/#how-to-get-consul-acl-token

**Comment by lenny-intel** [comment]
@bnevis-i , FYI

**Comment by bnevis-i** [comment]
To get the API token, instead use

```
make get-token
```

The kong-admin-jwt is used by security-proxy-setup to configure Kong and it can only access the /admin API.

**Comment by bnevis-i** [comment]
Closing as answered.
