### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by Vieufoux** [edgexfoundry/edgex-compose#39]
got this error when i make run:

/bin/sh: 1: cannot create ../releases/hanoi/taf/docker-compose-taf.yml: Directory nonexistent

**Comment by Vieufoux** [comment]
I can make run success after i created the taf director under edgex-compose/releases/hanoi directory manually

**Comment by lenny-intel** [comment]
@Vieufoux , need more details since I just successfully did a `make run`. What branch are you using? `master` or `hanoi`?
It shouldn't be trying to create that TAF compose file unless you run `make build` and since it is looking for the `hanoi` folder, I am assuming you are on the `hanoi` branch.

**Comment by Vieufoux** [comment]
Sorry i made a mistake, It's make build not make run.

1.I git clone the repo and it's master branch.
2.Enter into "compose-builder" directory and change the RELEASE=hanoi in .env file
3.make build

Then i met the error that i reported before

**Comment by lenny-intel** [comment]
`make build` is only for `pre-release`. 
If you what a new `hanoi` compose file, rather than run one. You MUST be on the `hanoi` branch and run `make gen [options]`

**Comment by jpwhitemn** [comment]
@Vieufoux - let us know if you have other questions or if you believe we still have not addressed your issue.  We can reopen as necessary.
