### ISSUE TITLE
Configure services to use the same timezone as the host

### ISSUE THREAD

**Issue by jackchenjc** [edgexfoundry/edgex-compose#393]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for the docker compose files enhancement

### Description [**REQUIRED**]
 By default, docker containers are using UTC time zone which may leads to inconsistent time zone problem between services and host in some services, e.g. support-scheduler.

### Describe the solution you'd like
 Set a "volumes" prop for each service to run the docker container with host timezone.
```
volumes:
      # use host timezone
      - /etc/localtime:/etc/localtime:ro
```

### Describe alternatives you've considered
 N/A

**Comment by cloudxxx8** [comment]
it will help the log time to use the host system timezone

**Comment by lenny-intel** [comment]
Based on my searching we should also mount. 
```
- "/etc/timezone:/etc/timezone:ro"
```

**Comment by jackchenjc** [comment]
Hi Lenny,

It seems that there might be cases where the `/etc/timezone` file is not present by default in certain operating systems, such as macOS and CentOS.

**Comment by lenny-intel** [comment]
@jackchenjc , Thanks for the info.
