### ISSUE TITLE
Error in generate ext service on macOS 

### ISSUE THREAD

**Issue by jiekechoo** [edgexfoundry/edgex-compose#418]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: compose-builder/gen_secure_compose_ext.sh

### Is this a regression?

 NO.

## 🔥 Exception or Error
<pre><code>

jiekechoo@jiekechoo compose-builder % uname -a
Darwin jiekechoo 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64
jiekechoo@jiekechoo compose-builder % make run arm64 ds-rest
sed: 1: "./gen_ext_compose/add-d ...": invalid command code .
sed: 1: "./gen_ext_compose/add-d ...": invalid command code .
sed: 1: "./gen_ext_compose/add-d ...": invalid command code .
echo MQTT_VERBOSE=
MQTT_VERBOSE=
docker compose  -p edgex -f docker-compose-base.yml -f add-device-rest.yml -f ./gen_ext_compose/add-device-rest-secure.yml -f add-security.yml -f add-secure-redis-messagebus.yml convert > docker-compose.yml
parsing /Users/jiekechoo/devel/edgex/edgex-compose/compose-builder/gen_ext_compose/add-device-rest-secure.yml: yaml: line 32: did not find expected ',' or ']'
make: *** [gen] Error 15
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@jiekechoo , very few of us use MAC, so well need your help in resolving this.
Please attach the generated `../compose-builder/gen_ext_compose/add-device-rest-secure.yml` file. You will need to temporarily  remove the `rm -rf ./$(GEN_EXT_DIR)` line from the `gen:` target in the Makefile so the file doesn't get removed.

**Comment by cloudxxx8** [comment]
@jiekechoo it's the `sed` syntax difference between MacOS and normal Linux.  The colleagues from my team with MacOS use a Linux VM to work on this.

**Comment by jiekechoo** [comment]
@cloudxxx8 OK, I'll close this issue.
