### ISSUE TITLE
Should we change the `core-common-config-bootstrapper` service start on boot?

### ISSUE THREAD

**Issue by jiekechoo** [edgexfoundry/edgex-compose#433]
https://github.com/edgexfoundry/edgex-compose/blob/55680017ff1b7c9db23deb52a21b27b28a7812ac/compose-builder/docker-compose-base.yml#L169-L191

**Comment by lenny-intel** [comment]
No, it only needs to run once to seed configuration. Doesn't help to rerun it once the configuration is seeded.
