### ISSUE TITLE
edgex-security-proxy-setup service fails to start after Ubuntu reboot

### ISSUE THREAD

**Issue by ethan256** [edgexfoundry/edgex-compose#434]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
When Ubuntu reboots, the proxy-setup service fails to start. This in turn causes the nginx container to fail to start properly.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]

```shell
git clone git@github.com:edgexfoundry/edgex-compose.git
git checkout tags/v3.1.0 -b release/3.1.0
cd compose-builder && make gen mqtt-broker ds-opcua ds-modbus ds-mqtt app-mqtt app-metric-process arm64
docker compose up -d
# wait service running and check
docker ps

# reboot system
sudo reboot
```

## 🔥 Exception or Error
<pre><code>

</code></pre>
![image](https://github.com/edgexfoundry/edgex-go/assets/46949410/2d1c9aa5-9cb2-4381-b5ef-1b8607e78b2f)

## 🌍  Your Environment
**Deployment Environment:**
os：  ubuntu 20.04 TLS
arch:  arm64
docker info:
![image](https://github.com/edgexfoundry/edgex-go/assets/46949410/9d381af4-0428-4764-82c8-bf4340b11b77)

**EdgeX Version [**REQUIRED**]:**
3.1.0

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@cherrycl please help add `restart: always` for both main and napa branches to resolve this issue
