### ISSUE TITLE
Remove unneeded edgex-kong network alias in napa branch

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-compose#435]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for api gateway

### Description [**REQUIRED**]
nginx doesn't need the edgex-kong network alias
Refer to: https://github.com/edgexfoundry/edgex-compose/pull/428

**Comment by cherrycl** [comment]
Fixed by #438
