### ISSUE TITLE
Consolidate App Service Export services to just secure or just non-secure for TAF tests

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-compose#59]
Currently the TAF secure compose file has both the secure and non-secure App Service export services (http & mqtt)

https://github.com/edgexfoundry/edgex-compose/blob/6f9eebdf77506cf97272d7f0462e8a1543fa0ec8/taf/docker-compose-taf.yml#L174-L318

https://github.com/edgexfoundry/edgex-compose/blob/6f9eebdf77506cf97272d7f0462e8a1543fa0ec8/taf/docker-compose-taf.yml#L174-L318

With the new Secure Consul access tokens the app service have to be run as "Secure" so it doesn't make sense to have both versions. Secure compose should have just one `app-service-export-http` and just one `app-service-export-mqtt`

**Comment by lenny-intel** [comment]
@cherrycl , @cloudxxx8 , how would this impact the TAF tests? 
Both secure and none-secure compose file would just have 
app-service-export-http and  app-service-export-mqtt, 
The `-secrets` versions would be removed.

**Comment by jim-wang-intel** [comment]
Hi @cloudxxx8 and @cherrycl  from the `edgex-compose` PR https://github.com/edgexfoundry/edgex-compose/pull/53, the `asc-x-secret` version have been changed to **extend** from its base version `asc-x`.  Please adjust or change the TAF test scripts accordingly and let us know how it fits.  Thanks! -Jim
