### ISSUE TITLE
Update to latest version of 3rd party dependencies

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-compose#76]
VAULT_VERSION=1.5.3 --> 1.7.1
CONSUL_VERSION=1.9.1 --> 1.9.5
REDIS_VERSION=6.0.9-alpine --> 6.2.3-alpine
KONG_VERSION=2.3-alpine --> 2.4.0-alpine
MOSQUITTO_VERSION=1.6.3 --> 2.0.10

**Comment by jim-wang-intel** [comment]
There are some breaking changes in Vault API JSON response for the version after 1.6.x  if I remember right. So we need to fix these first before we can upgrade Vault beyond 1.5.x

**Comment by lenny-intel** [comment]
@jim-wang-intel , Interestingly it doesn't look to be an issue. PR #77 is passing Smoke Tests.

Maybe Vault reverted that change since the until 2.0 version since it is a breaking change. Thought I had head something about that. @bnevis-i any insight here.?

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel , Interestingly it doesn't look to be an issue. PR #77 is passing Smoke Tests.
> 

@lenny-intel   ok, but passing TAF doesn't mean we don't have an issue here- maybe TAF doesn't cover test that part of code.  I think we need to look deeper into it.

**Comment by bnevis-i** [comment]
Predicted disaster with the Vault version change didn't occur.  Still seems to be using the same json keys as the older versions.

**Comment by lenny-intel** [comment]
@jim-wang-intel , that issue would tank security services to start-up. @bnevis-i agrees and has closed his issue. PR merged.

**Comment by lenny-intel** [comment]
Neglected to rebuild the compose files in the #77 so reopening this issue and submitted #78

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel , that issue would tank security services to start-up. @bnevis-i agrees and has closed his issue. PR merged.

awesome, then no more concerns from me, thank you and @bnevis-i .
