### ISSUE TITLE
edgex started incorrectly

### ISSUE THREAD

**Issue by Qinyong-Li** [edgexfoundry/edgex-compose#84]
I just run edgex with docker-compose-no-secty.yml.

edgex-app-service-configurable-rules | level=ERROR ts=2021-05-10T07:49:09.095635923Z app=app-rules-engine source=config.go:172 msg="configuration provider is not available"
edgex-sys-mgmt-agent | level=ERROR ts=2021-05-10T07:49:09.101871994Z app=edgex-sys-mgmt-agent source=config.go:172 msg="configuration provider is not available"
edgex-support-notifications | level=ERROR ts=2021-05-10T07:49:09.980450792Z app=edgex-support-notifications source=config.go:172 msg="configuration provider is not available"
edgex-core-command   | level=ERROR ts=2021-05-10T07:49:09.989219863Z app=edgex-core-command source=config.go:172 msg="configuration provider is not available"
edgex-support-scheduler | level=ERROR ts=2021-05-10T07:49:09.989764062Z app=edgex-support-scheduler source=config.go:172 msg="configuration provider is not available"
edgex-core-data      | level=ERROR ts=2021-05-10T07:49:09.990050668Z app=edgex-core-data source=config.go:172 msg="configuration provider is not available"
edgex-core-metadata  | level=ERROR ts=2021-05-10T07:49:09.992159592Z app=edgex-core-metadata source=config.go:172 msg="configuration provider is not available"
edgex-device-rest    | level=ERROR ts=2021-05-10T07:49:10.083562861Z app=edgex-device-rest source=config.go:172 msg="configuration provider is not available"
edgex-device-virtual | level=ERROR ts=2021-05-10T07:49:10.088153312Z app=device-virtual source=config.go:172 msg="configuration provider is not available"

**Comment by lenny-intel** [comment]
@Qinyong-Li , how are running the compose file? Have you tried the `make run no-secty' convenience command?
See [README ](https://github.com/edgexfoundry/edgex-compose/blob/master/README.md) for details

**Comment by Qinyong-Li** [comment]
@lenny-intel I have tried "no-secty", but failed

**Comment by lenny-intel** [comment]
@Qinyong-Li , This works fine for me.
We need more details on exactly the command(s) you are using to run.

Also, you should always first run `make clean` first to stop all existing services and remove containers, volumes and networks.

**Comment by Qinyong-Li** [comment]
I just use "docker-compose  up " with docker-compose-no-secty.yml, and “make clean” is useless.

I  have run edges on a virtual machine, thank you.

**Comment by jim-wang-intel** [comment]
Hi @Qinyong-Li , 
  The best way to run the EdgeX docker stack is through the `make` target commands.  Those `make` commands are run underneath the directory of `edgex-compose/compose-builders`. 

So with the case you want to run with `no-security` mode, you can do the following steps:

1. Change your directory to `compose-builders` from the base of `edgex-compose`:  cd ./compose-builder

2. Clean up the potential left-over volumes from previous states: execute command on the console with `make clean`

3. Run the `no-secty` make target command via `make run no-secty`.

**Comment by Qinyong-Li** [comment]
@jim-wang-intel  thank you, I have run it with your solution.
