### ISSUE TITLE
Incorrect hostname of EDGEX__DEFAULT__SERVICESERVER on rulesengine service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-compose#93]
The value of `EDGEX__DEFAULT__SERVICESERVER` should be `http://edgex-core-metadata:48081`.
https://github.com/edgexfoundry/edgex-compose/blob/912156824d4345c522ad3f331065b801255f93f9/taf/docker-compose-taf.yml#L1037

**Comment by lenny-intel** [comment]
Closing this issue this setting goes away when we integrate the V2 supported version of Kuiper
